# Generated by Django 5.1.1 on 2024-09-22 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='position',
        ),
    ]
